# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wished_by',
            field=models.ManyToManyField(related_name='my_wishlists', to='wishlist.User'),
        ),
    ]
