# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_auto_20180417_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user', to='wishlist.User'),
        ),
    ]
